// Netlify build script - injects API key from environment variable
const fs = require('fs');
const path = require('path');

const API_KEY = process.env.WEATHER_API_KEY || '';

if (!API_KEY) {
    console.error('❌ WEATHER_API_KEY not set - build will fail');
    console.error('Please add WEATHER_API_KEY in Netlify environment variables');
    process.exit(1);
}

const config = `// Auto-generated by build
window.WEATHER_CONFIG = { API_KEY: '${API_KEY}' };
`;

const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, config, 'utf8');
console.log('✅ API key configured at:', configPath);
console.log('✅ config.js created successfully');
