// Netlify build script - injects API key from environment variable
const fs = require('fs');
const path = require('path');

const API_KEY = process.env.WEATHER_API_KEY || '';

if (!API_KEY) {
    console.warn('⚠️  WEATHER_API_KEY not set - app will not work');
    process.exit(0);
}

const config = `// Auto-generated by build
window.WEATHER_CONFIG = { API_KEY: '${API_KEY}' };
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), config, 'utf8');
console.log('✅ API key configured');
